# Generated by Django 5.2.5 on 2025-08-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetalsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('palladium', 'Palladium')], max_length=20)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'unique_together': {('metal', 'date')},
            },
        ),
    ]
