# Generated by Django 5.2.5 on 2025-08-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetalsPrice',
        ),
    ]
